apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: keptn/new-configuration-service
      docker:
        dockerfile: Dockerfile
        target: production
deploy:
  kubectl:
    defaultNamespace: keptn
    manifests:
      - deploy/service.yaml
